-- Demo-Schema für die MES-Demo-Umgebung.
-- Läuft beim ersten Start des Oracle-Containers (gvenzl/oracle-free) als SYS.
--
-- Nachbildung beim Kunden:
--   MES_LOCAL   ↔  MES_Connection         (lokale Landes-DB, maxActive 50)
--   MES_MASTER  ↔  Master_MES_Connection  (Master-DB, maxActive 20)
--   MES_REPL    ↔  Replikationsmechanismus, der Tabellen sperrt
--   MES_MONITOR ↔  Lesezugriff auf V$-Views für das Lock-Monitoring
-- Beim Kunden sind lokale und Master-DB getrennte Datenbanken; hier sind es
-- zwei Schemas in derselben PDB.

ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER mes_local   IDENTIFIED BY "mes_demo" DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
CREATE USER mes_master  IDENTIFIED BY "mes_demo" DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
CREATE USER mes_repl    IDENTIFIED BY "mes_demo";
CREATE USER mes_monitor IDENTIFIED BY "mes_demo";

GRANT CREATE SESSION TO mes_local, mes_master, mes_repl, mes_monitor;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO mes_local, mes_master;

-- Monitoring-User: nur lesend auf das Data Dictionary (V$SESSION, V$LOCK, DBA_OBJECTS …)
GRANT SELECT ANY DICTIONARY TO mes_monitor;

-- ─── Lokale Datenbank ──────────────────────────────────────────────────────
CREATE TABLE mes_local.baugruppe (
  id            NUMBER        PRIMARY KEY,
  seriennummer  VARCHAR2(30)  NOT NULL,
  artikel       VARCHAR2(30)  NOT NULL,
  status        VARCHAR2(20)  NOT NULL,
  station       VARCHAR2(20),
  buchungen     NUMBER        DEFAULT 0 NOT NULL,
  geaendert     TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE TABLE mes_local.buchung (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  baugruppe_id  NUMBER        NOT NULL,
  station       VARCHAR2(20),
  ergebnis      VARCHAR2(10),
  zeitpunkt     TIMESTAMP     DEFAULT SYSTIMESTAMP
);

INSERT INTO mes_local.baugruppe (id, seriennummer, artikel, status, station)
  SELECT level,
         'SN-' || LPAD(level, 8, '0'),
         'ART-' || MOD(level, 200),
         CASE MOD(level, 4) WHEN 0 THEN 'FERTIG' WHEN 1 THEN 'SMT' WHEN 2 THEN 'AOI' ELSE 'PRUEFUNG' END,
         'STATION-' || MOD(level, 12)
    FROM dual CONNECT BY level <= 10000;

-- ─── Master-Datenbank ──────────────────────────────────────────────────────
CREATE TABLE mes_master.stammdaten (
  id            NUMBER        PRIMARY KEY,
  artikel       VARCHAR2(30)  NOT NULL,
  bezeichnung   VARCHAR2(100),
  version       NUMBER        DEFAULT 1 NOT NULL,
  geaendert     TIMESTAMP     DEFAULT SYSTIMESTAMP
);

INSERT INTO mes_master.stammdaten (id, artikel, bezeichnung)
  SELECT level, 'ART-' || level, 'Artikel Nummer ' || level
    FROM dual CONNECT BY level <= 2000;

COMMIT;

-- Der "Replikationsprozess" darf beide Tabellen sperren (LOCK TABLE braucht ein Objektprivileg)
GRANT SELECT, UPDATE ON mes_local.baugruppe   TO mes_repl;
GRANT SELECT, UPDATE ON mes_master.stammdaten TO mes_repl;
